//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 05:26:22 PM IST 
//


package XML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import Adapters.*;
import Algorithms.*;
import Encryptors.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inputPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="action_Taken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encryptor_Used" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Algorithm_Used" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Key_Path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outPutPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputPath",
    "actionTaken",
    "encryptorUsed",
    "algorithmUsed",
    "keyPath",
    "outPutPath"
})
@XmlRootElement(name = "Run_Results")
public class RunResults extends Data {

    @XmlElement(required = true)
    protected String inputPath;
    @XmlElement(name = "action_Taken", required = true)
    protected String actionTaken;
    @XmlElement(name = "encryptor_Used", required = true)
	@XmlJavaTypeAdapter( EncryptorAdapter.class )
    protected Encryptor encryptorUsed;
    @XmlElement(name = "Algorithm_Used", required = true)
	@XmlJavaTypeAdapter( EncryptionAlgorithmAdapter.class )
    protected EncryptionAlgorithm algorithmUsed;
    @XmlElement(name = "Key_Path", required = true)
    protected String keyPath;
    @XmlElement(required = true)
    protected String outPutPath;

    /**
     * Gets the value of the inputPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputPath() {
        return inputPath;
    }

    /**
     * Sets the value of the inputPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputPath(String value) {
        this.inputPath = value;
    }

    /**
     * Gets the value of the actionTaken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionTaken() {
        return actionTaken;
    }

    /**
     * Sets the value of the actionTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionTaken(String value) {
        this.actionTaken = value;
    }

    /**
     * Gets the value of the encryptorUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Encryptor getEncryptorUsed() {
        return encryptorUsed;
    }

    /**
     * Sets the value of the encryptorUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptorUsed(Encryptor value) {
        this.encryptorUsed = value;
    }

    /**
     * Gets the value of the algorithmUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public EncryptionAlgorithm getAlgorithmUsed() {
        return algorithmUsed;
    }

    /**
     * Sets the value of the algorithmUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithmUsed(EncryptionAlgorithm value) {
        this.algorithmUsed = value;
    }

    /**
     * Gets the value of the keyPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPath() {
        return keyPath;
    }

    /**
     * Sets the value of the keyPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPath(String value) {
        this.keyPath = value;
    }

    /**
     * Gets the value of the outPutPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutPutPath() {
        return outPutPath;
    }

    /**
     * Sets the value of the outPutPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutPutPath(String value) {
        this.outPutPath = value;
    }
    
    public String toString() {
    	return "RunResults";
    }

}
